In [1]:
import pandas as pd
df=pd.read_csv("weight-height.csv")
df

      Gender     Weight      Height
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [2]:
df.groupby("Gender").mean() #Average Height And Weight of Gender

           Weight      Height
Gender
Female  63.708774  135.860093
Male    69.026346  187.020621

In [3]:
df.groupby("Gender").Weight.agg(["min","max"]) # min and max weight of gender

              min        max
Gender
Female  54.263133  73.389586
Male    58.406905  78.998742

In [4]:
short=df[df["Height"]<160]  # splits in three categories for counting
average=df[(df["Height"]>=160) & (df["Height"]<180)]
tall=df[df["Height"]>=180]

print("Short :",short.Gender.count())
print()
print("Average :",average.Gender.count())
print()
print("Tall :",tall.Gender.count())

Short : 4892

Average : 1878

Tall : 3230

In [5]:
print("Short :",short.Weight.mean())  # Average Weights of categories hight
print()
print("Average :",average.Weight.mean())
print()
print("Tall :",tall.Weight.mean())

Short : 63.345568567810716

Average : 67.19351062038871

Tall : 70.46429200304644

In [6]:
df.groupby("Gender").Weight.std() #Standard Deviation

Gender
Female    2.696284
Male      2.863362
Name: Weight, dtype: float64

In [7]:
print(short.Gender.value_counts())

Gender
Female    4471
Male       421
Name: count, dtype: int64

In [8]:
print(average.Gender.value_counts())

Gender
Male      1396
Female     482
Name: count, dtype: int64

In [9]:
print(tall.Gender.value_counts())

Gender
Male      3183
Female      47
Name: count, dtype: int64