In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("restaurant.csv")

In [4]:
avg_male_tip=df[df.gender=="Male"].tip.mean() # Average Male Tip
avg_female_tip=df[df.gender=="Female"].tip.mean() # Average Female Tip
print(avg_male_tip)
print(avg_female_tip)

3.0896178343949043
2.8334482758620685

In [5]:
df.groupby(by=["day"]).total_bill.agg(["mean"]) # Per Day Average Bill

           mean
day
Fri   17.151579
Sat   20.441379
Sun   21.410000
Thur  17.682742

In [6]:
df.groupby(by=["smoker"]).tip.agg(["mean"]) # Tip By Smoker and Non Smoker

            mean
smoker
No      2.991854
Yes     3.008710

In [7]:
a=df["time"] # Count Dinner And Lunch
dinner=0 
lunch=0
for i in a:
    if i=="Dinner":
        dinner=dinner+1
    elif i=="Lunch":
        lunch=lunch+1
print(dinner)
print(lunch)

176
68

In [8]:
df.groupby('day')[['total_bill', 'size']].agg({'total_bill': 'count', 'size': 'mean'}) # per day customer count and avg table size

      total_bill      size
day
Fri           19  2.105263
Sat           87  2.517241
Sun           76  2.842105
Thur          62  2.451613

In [9]:
df.groupby(by=["gender","smoker"]).tip.agg(["mean"]) # Gender And Smoker Wise Average Tip

                   mean
gender smoker
Female No      2.773519
       Yes     2.931515
Male   No      3.113402
       Yes     3.051167

In [10]:
df.groupby(by="size").total_bill.agg(["mean"]) # Average Total Bill By TableSize

           mean
size
1      7.242500
2     16.448013
3     23.277632
4     28.613514
5     30.068000
6     34.830000

In [11]:
df.groupby("day").tip.agg(["sum"])

         sum
day
Fri    51.96
Sat   260.40
Sun   247.39
Thur  171.83