In [1]:
import pandas as pd
df=pd.read_csv("sachin_odi.csv")
df.head(10)

,batting_score,wickets,runs_conceded,catches,stumps,opposition,ground,date,match_result,result_margin,toss,batting_innings
0,0,-,-,0,0,v Pakistan,Gujranwala,18-Dec-89,lost,7 runs,won,2nd
1,0,-,-,0,0,v New Zealand,Dunedin,1-Mar-90,lost,108 runs,won,2nd
2,36,-,-,0,0,v New Zealand,Wellington,6-Mar-90,won,1 runs,won,1st
3,10,-,-,1,0,v Sri Lanka,Sharjah,25-Apr-90,lost,3 wickets,lost,1st
4,20,-,-,0,0,v Pakistan,Sharjah,27-Apr-90,lost,26 runs,won,2nd
5,19,-,-,0,0,v England,Leeds,18-Jul-90,won,6 wickets,won,2nd
6,31,0,10,0,0,v England,Nottingham,20-Jul-90,won,5 wickets,won,2nd
7,36,-,-,0,0,v Sri Lanka,Nagpur,1-Dec-90,won,19 runs,lost,1st
8,53,2,39,2,0,v Sri Lanka,Pune,5-Dec-90,won,6 wickets,won,2nd
9,30,-,-,0,0,v Sri Lanka,Margao,8-Dec-90,lost,7 wickets,won,1st

In [2]:
df["batting_score"] = pd.to_numeric(df["batting_score"], errors='coerce')

In [3]:
# Q1. Jab India jeet ti thi aur jab harti thi — dono mein Sachin ka average batting score compare karo.

df.groupby("match_result").batting_score.agg(["mean"])

                   mean
match_result
lost          32.131313
n/r           31.363636
tied          33.200000
won           42.284264

In [4]:
# Q2. Har team (opposition) ke against kitne matches khele gaye? Sabse zyada matches kis team ke against the?

df.groupby("opposition").opposition.agg(["count"])

                count
opposition
v Australia        71
v Bangladesh       12
v Bermuda           1
v England          37
v Ireland           2
v Kenya            10
v Namibia           1
v Netherlands       2
v New Zealand      42
v Pakistan         69
v South Africa     57
v Sri Lanka        84
v U.A.E.            2
v West Indies      39
v Zimbabwe         34

In [5]:
# Q3. Toss jeeta ya haara — dono cases mein matches ka count karo. Toss ka match result pe kya asar tha?

df.groupby(["toss"]).toss.agg(["count"])

      count
toss
lost    224
won     239

In [6]:
df.groupby("match_result").match_result.agg(["count"]) #Que3

              count
match_result
lost            200
n/r              24
tied              5
won             234

In [7]:
# Q4. Pehli innings mein batting ki ya doosri mein — dono mein average score compare karo.

df.groupby("batting_innings").batting_score.agg(["mean","min","max"])

                      mean  min    max
batting_innings
1st              40.668293  0.0  152.0
2nd              33.330097  0.0  175.0

In [8]:
# Q5. Har team ke against Sachin ka average batting score kya tha? Kis team ke against sabse zyada runs banaye?

df.groupby("opposition").batting_score.agg(["mean"])

                      mean
opposition
v Australia      42.898551
v Bangladesh     41.400000
v Bermuda              NaN
v England        35.515152
v Ireland        21.000000
v Kenya          46.666667
v Namibia       152.000000
v Netherlands    39.500000
v New Zealand    35.605263
v Pakistan       36.603175
v South Africa   32.160714
v Sri Lanka      38.014085
v U.A.E.         40.500000
v West Indies    31.133333
v Zimbabwe       33.214286

In [9]:
# Q6. Match result aur toss dono ka combination groupby karo — 4 groups ka match count compare karo.

df.groupby(["match_result","toss"]).match_result.agg(["count"]).head(16)

                   count
match_result toss
lost         lost     99
             won     101
n/r          lost     12
             won      12
tied         lost      4
             won       1
won          lost    109
             won     125

In [10]:
# Q7. Har team ke against jeetne wale aur haarne wale matches alag count karo.

df.groupby(["opposition","match_result"]).match_result.agg(["count"])

                             count
opposition     match_result
v Australia    lost             44
               n/r               4
               won              23
v Bangladesh   lost              2
               won              10
v Bermuda      won               1
v England      lost             15
               n/r               2
               tied              1
               won              19
v Ireland      won               2
v Kenya        lost              2
               won               8
v Namibia      won               1
v Netherlands  won               2
v New Zealand  lost             15
               n/r               5
               won              22
v Pakistan     lost             36
               n/r               2
               won              31
v South Africa lost             35
               n/r               1
               won              21
v Sri Lanka    lost             31
               n/r               9
               tied              1
               won              43
v U.A.E.       won               2
v West Indies  lost             15
               n/r               1
               tied              1
               won              22
v Zimbabwe     lost              5
               tied              2
               won              27

In [11]:
# Q8. Batting innings (1st/2nd) aur match result ka combination — 2nd innings mein batting karne pe zyada jeete?

df.groupby(["batting_innings","match_result"]).match_result.agg(["count"])

                              count
batting_innings match_result
1st             lost             99
                n/r              12
                tied              3
                won             107
2nd             lost            101
                n/r              12
                tied              2
                won             127