In [1]:
import pandas as pd
df=pd.read_csv("salaray_projects.csv")
df

    WorkExp  Projects  Salary
0       1.1         1   39343
1       1.3         2   46205
2       1.5         3   37731
3       2.0         4   43525
4       2.2         5   39891
5       2.9         6   56642
6       3.0         7   60150
7       3.2         8   54445
8       3.2         9   64445
9       3.7        10   57189
10      3.9        11   63218
11      4.0        12   55794
12      4.0        13   56957
13      4.1        14   57081
14      4.5        15   61111
15      4.9        16   67938
16      5.1        17   66029
17      5.3        18   83088
18      5.9        19   81363
19      6.0        20   93940
20      6.8        21   91738
21      7.1        22   98273
22      7.9        23  101302
23      8.2        24  113812
24      8.7        25  109431
25      9.0        26  105582
26      9.5        27  116969
27      9.6        28  112635
28     10.3        29  122391
29     10.5        30  121872

In [2]:
df.groupby("Projects").Salary.mean() # Average Salary By Projects

Projects
1      39343.0
2      46205.0
3      37731.0
4      43525.0
5      39891.0
6      56642.0
7      60150.0
8      54445.0
9      64445.0
10     57189.0
11     63218.0
12     55794.0
13     56957.0
14     57081.0
15     61111.0
16     67938.0
17     66029.0
18     83088.0
19     81363.0
20     93940.0
21     91738.0
22     98273.0
23    101302.0
24    113812.0
25    109431.0
26    105582.0
27    116969.0
28    112635.0
29    122391.0
30    121872.0
Name: Salary, dtype: float64

In [3]:
max_sal=df["Salary"].max() # Max Salary And Minimum Salary
min_sal=df["Salary"].min()
print("Maximun Salary :",max_sal)
print()
print("Minimun Salary :",min_sal)

Maximun Salary : 122391

Minimun Salary : 37731

In [4]:
import numpy as np
import statistics as st 
a=df["WorkExp"]
print(st.quantiles(a))

[3.1500000000000004, 4.7, 7.9750000000000005]

In [7]:
three=df[df["WorkExp"]<3] # Work experince 0-3
seven=df[(df["WorkExp"]>=3) & (df["WorkExp"]<7)] # Work experince 3-7
ten=df[df["WorkExp"]>=7] # Work experince 7+

print("Work Exp 0-3 Average Salary :",three.Salary.mean())
print()
print("Work Exp 3-7 Average Salary :",seven.Salary.mean())
print()
print("Work Exp 7+ Average Salary :",ten.Salary.mean())

Work Exp 0-3 Average Salary : 43889.5

Work Exp 3-7 Average Salary : 67632.4

Work Exp 7+ Average Salary : 111363.0

In [8]:
under50=df[df["Salary"]<=50000]
above50=df[df["Salary"]>50000]
print("Average Work Exp Of Above 50 Thousand Salaried Employee :",above50.WorkExp.mean())
print("Average Work Exp Of Under 50 Thousand Salaried Employee :",under50.WorkExp.mean())

Average Work Exp Of Above 50 Thousand Salaried Employee : 6.0520000000000005
Average Work Exp Of Under 50 Thousand Salaried Employee : 1.6200000000000003

In [9]:
df.describe()

         WorkExp   Projects         Salary
count  30.000000  30.000000      30.000000
mean    5.313333  15.500000   76003.000000
std     2.837888   8.803408   27414.429785
min     1.100000   1.000000   37731.000000
25%     3.200000   8.250000   56720.750000
50%     4.700000  15.500000   65237.000000
75%     7.700000  22.750000  100544.750000
max    10.500000  30.000000  122391.000000